// ============================================================
// app/auth/callback/page.tsx
// Handles the Supabase OAuth redirect (Google etc.) CLIENT-SIDE.
//
// WHY CLIENT-SIDE:
//   The browser uses the PKCE flow (supabase-js default). The
//   `code_verifier` generated by signInWithOAuth lives in the
//   browser's storage, so the code↔session exchange MUST happen
//   in the browser — a server route handler has no verifier and
//   the exchange always fails. This mirrors the native deep-link
//   handler in components/native/CapacitorInit.tsx.
// ============================================================
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { getSupabaseBrowserClient } from '@/lib/hooks/useAuth'

export default function AuthCallbackPage() {
  const router = useRouter()
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const next = params.get('next') ?? '/'
    const safePath = next.startsWith('/') && !next.startsWith('//') ? next : '/'
    const code = params.get('code')
    const sb = getSupabaseBrowserClient()

    let cancelled = false

    async function finish() {
      if (code) {
        const { error } = await sb.auth.exchangeCodeForSession(code)
        if (error) {
          // `detectSessionInUrl` may have already consumed the code on
          // client init — treat as success if a session now exists.
          const { data } = await sb.auth.getSession()
          if (!data.session) {
            if (!cancelled) {
              setFailed(true)
              router.replace('/?auth_error=true')
            }
            return
          }
        }
      }
      if (!cancelled) router.replace(safePath)
    }

    finish()
    return () => {
      cancelled = true
    }
  }, [router])

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 14,
        background: 'var(--off-white, #fafaf8)',
        fontFamily: 'var(--font-body)',
      }}
    >
      {!failed && (
        <span
          style={{
            width: 26,
            height: 26,
            border: '3px solid var(--b2, #e7e5e0)',
            borderTop: '3px solid var(--forest-mid, #1b7f4f)',
            borderRadius: '50%',
            animation: 'spin 0.7s linear infinite',
            display: 'inline-block',
          }}
        />
      )}
      <p style={{ margin: 0, fontSize: 14, color: 'var(--ink-60, #6b6862)' }}>
        {failed ? 'Échec de la connexion. Redirection…' : 'Connexion en cours…'}
      </p>
    </div>
  )
}
